// Generates CSS custom properties and the Tailwind theme mapping from docs/design/tokens.json.
// Run: node scripts/build-tokens.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(resolve(root, "docs/design/tokens.json"), "utf8"));

const { dark, ...light } = tokens.color;
const vars = (obj, indent = "  ") =>
  Object.entries(obj)
    .map(([k, v]) => `${indent}--c-${k}: ${v};`)
    .join("\n");

const px = (n) => `${n}px`;
const rem = (n) => `${n / 16}rem`;

const staticVars = [
  ...Object.entries(tokens.font).map(([k, v]) => `  --f-${k}: ${v};`),
  ...Object.entries(tokens.radius).map(([k, v]) => `  --r-${k}: ${px(v)};`),
  ...Object.entries(tokens.shadow).map(([k, v]) => `  --sh-${k}: ${v};`),
  ...Object.entries(tokens.motion).map(([k, v]) => `  --m-${k}: ${v};`),
  `  --l-sidebar: ${px(tokens.layout.sidebar)};`,
  `  --l-header: ${px(tokens.layout.header)};`,
  `  --l-read: ${px(tokens.layout["read-column"])};`,
  `  --l-workspace: ${px(tokens.layout["workspace-max"])};`,
].join("\n");

const tokensCss = `/* Generated by scripts/build-tokens.mjs from docs/design/tokens.json. Do not edit. */
:root {
  color-scheme: light;
${vars(light)}
${staticVars}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${vars(dark, "    ")}
    --sh-card: 0 1px 0 rgba(0,0,0,.3), 0 1px 2px rgba(0,0,0,.4);
    --sh-pop: 0 16px 40px rgba(0,0,0,.6);
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${vars(dark)}
  --sh-card: 0 1px 0 rgba(0,0,0,.3), 0 1px 2px rgba(0,0,0,.4);
  --sh-pop: 0 16px 40px rgba(0,0,0,.6);
}
`;

const themeCss = `/* Generated by scripts/build-tokens.mjs. Maps tokens into Tailwind v4 so components use
   bg-surface, text-muted, rounded-md and never raw hex. Do not edit. */
@theme inline {
  --color-*: initial;
${Object.keys(light)
  .map((k) => `  --color-${k === "text-muted" ? "muted" : k}: var(--c-${k});`)
  .join("\n")}
  --color-transparent: transparent;
  --color-current: currentColor;

  --font-serif: var(--f-serif);
  --font-sans: var(--f-sans);
  --font-mono: var(--f-mono);

${Object.entries(tokens.type)
  .map(
    ([k, t]) =>
      `  --text-${k}: ${rem(t.size)};\n  --text-${k}--line-height: ${rem(t.line)};\n  --text-${k}--font-weight: ${t.weight};`,
  )
  .join("\n")}

  --radius-*: initial;
${Object.keys(tokens.radius)
  .map((k) => `  --radius-${k}: var(--r-${k});`)
  .join("\n")}

  --shadow-*: initial;
  --shadow-card: var(--sh-card);
  --shadow-pop: var(--sh-pop);

  --breakpoint-*: initial;
${Object.entries(tokens.layout.breakpoints)
  .map(([k, v]) => `  --breakpoint-${k}: ${px(v)};`)
  .join("\n")}

  --ease-out: var(--m-ease);
}
`;

for (const dir of ["src/styles"]) {
  mkdirSync(resolve(root, dir), { recursive: true });
  writeFileSync(resolve(root, dir, "tokens.css"), tokensCss);
  writeFileSync(resolve(root, dir, "tailwind-theme.css"), themeCss);
}
console.log("tokens.css and tailwind-theme.css written to src/styles");
